version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  migrations:
    image: semtech/mu-migrations-service:0.5.0
    links:
      - db:database
    volumes:
      - ./config/migrations:/data/migrations
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  microservicerevisionservice:
    image: semtech/microservice-revision-service:0.0.5
    links:
      - db:database
